name: Provision azure resources

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "App name"
      subscriptionId:
        description: "Azure subscription id"
      resourceGroupName:
        description: "Azure resource group name"

jobs:
  deployArmJob:
    name: Deploy ARM templates
    outputs:
      keyVaultName: ${{ steps.deployArm.outputs.keyVaultName }}
      sqlServerName: ${{ steps.deployArm.outputs.sqlServerName }}
      webAppName: ${{ steps.deployArm.outputs.webAppName }}
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Github checkout
        uses: actions/checkout@v2

      - uses: whiteducksoftware/azure-arm-action-js@v4
        id: deployArm
        with:
          scope: resourcegroup
          subscriptionId: ${{ github.event.inputs.subscriptionId }}
          resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
          templateLocation: ./src/Infrastructure/Cloud/Arm/link-template.json
          parameters: ./src/Infrastructure/Cloud/Arm/link-template.json
            appName=${{ github.event.inputs.appName }}-overriden
            githubRepository=$GITHUB_REPOSITORY-overriden

  createDbMsiUser:
    needs: deployArmJob
    name: Add Web App MSI user to database
    runs-on: windows-latest
    steps:
      - uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: ${{ needs.deployArmJob.outputs.keyVaultName }}
          secrets: "AzureSqlDbAdminPassword"

      - uses: actions/checkout@master
      - name: Replace web app name in SQL script for adding MSI user
        uses: shitiomatic/str-replace@master
        with:
          find: "web-app-name"
          replace: ${{ needs.deployArmJob.outputs.webAppName }}

      - uses: azure/sql-action@v1
        with:
          server-name: ${{ needs.deployArmJob.outputs.sqlServerName }}
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          sql-file: "./src/Infrastructure/Cloud/AzureSqlDb/msi-user.sql"
