name: Provision azure resources

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "App name"
      subscriptionId:
        description: "Azure subscription id"
      resourceGroupName:
        description: "Azure resource group name"
      dbAdminUserName:
        description: "User name of database admin"

jobs:
  deployArmJob:
    name: Deploy ARM templates
    outputs:
      almKeyVaultName: ${{ steps.deployArm.outputs.almKeyVaultName }}
      sqlServerName: ${{ steps.deployArm.outputs.sqlServerName }}
      sqlDbName: ${{ steps.deployArm.outputs.sqlDbName }}
      webAppName: ${{ steps.deployArm.outputs.webAppName }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Github checkout
        uses: actions/checkout@v2

      - name: Deploy ARM templates
        uses: whiteducksoftware/azure-arm-action-js@v4
        id: deployArm
        with:
          scope: resourcegroup
          subscriptionId: ${{ github.event.inputs.subscriptionId }}
          resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
          templateLocation: "./src/Infrastructure/Cloud/Arm/link-template.json"
          parameters: appName=${{ github.event.inputs.appName }}
            dbAdminAadObjectId=${{ secrets.AZURE_DB_ADMIN_AAD_OBJECT_ID }}
            githubRepository=${{ github.repository }}

  createDbMsiUser:
    needs: deployArmJob
    name: Add Web App MSI user to database
    runs-on: windows-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Github checkout
        uses: actions/checkout@v2

      - name: Replace web app name in SQL script for adding MSI user
        run: |
          ((Get-Content -path  .\src\Infrastructure\Cloud\AzureSqlDb\msi-user.sql).replace('web-app-name','${{ needs.deployArmJob.outputs.webAppName }}') | Set-Content -Path .\src\Infrastructure\Cloud\AzureSqlDb\msi-user.sql)

      - name: Run SQL script to add MSI user to database
        run: SQLCMD.exe -S ${{ needs.deployArmJob.outputs.sqlServerName }}.database.windows.net -d ${{ needs.deployArmJob.outputs.sqlDbName }} -U $${{github.event.inputs.dbAdminUserName}} -P ${{ secrets.AZURE_DB_ADMIN_PASSWORD }} -i ./src/Infrastructure/Cloud/AzureSqlDb/msi-user.sql -G
