name: Provision azure resources

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: "Azure resource group."
      dbAdminObjectId:
        description: "Azure active directory object id of the database admin user."

jobs:
  deployment:
    name: Deploy ARM templates
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Github checkout
        uses: actions/checkout@v2

      - name: Validate ARM deployment
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az group deployment validate -g ${{ github.event.inputs.resourceGroupName }} \
            --template-file $GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template.json \
            --parameters @$GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template-parameters.json  \
            --parameters dbAdminAadObjectId=${{ github.event.inputs.dbAdminObjectId }}

      - name: Deploy ARM templates
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az group deployment create -g ${{ github.event.inputs.resourceGroupName }} \
            --template-file $GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template.json \
            --parameters @$GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template-parameters.json  \
            --parameters dbAdminAadObjectId=${{ github.event.inputs.dbAdminObjectId }}
