name: Provision azure resources

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "App name"
      resourceGroupName:
        description: "Azure resource group name"

jobs:
  deployArm:
    name: Deploy ARM templates
    runs-on: ubuntu-latest
    outputs:
      keyVaultName: ${{ steps.deployArm.outputs.keyVaultName }}
      sqlServerName: ${{ steps.deployArm.outputs.sqlServerName }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Github checkout
        uses: actions/checkout@v2

      - name: Validate ARM deployment
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group validate -g ${{ github.event.inputs.resourceGroupName }} \
            --template-file $GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template.json \
            --parameters @$GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template-parameters.json  \
            --parameters appName=${{ github.event.inputs.appName }} githubRepository=$GITHUB_REPOSITORY

      - name: Deploy ARM templates
        id: deployArm
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group create -g ${{ github.event.inputs.resourceGroupName }} \
            --template-file $GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template.json \
            --parameters @$GITHUB_WORKSPACE/src/Infrastructure/Cloud/Arm/link-template-parameters.json  \
            --parameters appName=${{ github.event.inputs.appName }} githubRepository=$GITHUB_REPOSITORY

  createDbMsiUser:
    needs: deployArm
    name: Add Web App MSI user to database
    runs-on: windows-latest
    steps:
      - uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: ${{ needs.deployArm.outputs.keyVaultName }}
          secrets: "AzureSqlDbAdminPassword"

      - uses: azure/sql-action@v1
        with:
          server-name: ${{ needs.deployArm.outputs.sqlServerName }}
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          sql-file: "./src/Infrastructure/Cloud/AzureSqlDb/msi-user.sql"
