name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"

      #Checkout code
      - name: Github checkout
        uses: actions/checkout@v2

      #Setup, build and test app
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish --configuration Release -o reactdotnet
        env:
          CI: false
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      #Publish app to azure using web app publish profile
      - uses: azure/webapps-deploy@v2
        with:
          package: "./reactdotnet"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
